### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by jaydangar** [narVidhai/Google-Transliterate-API#2]
Hello @GokulNC , Can you provide API documentation link for the transliteration API, because since it's deprecated i can't find the documentation, right now I have created a dart package which takes input and returns the 5 tranliterations of the give input. I need to add more functionalities if possible. can you provide me the documentation so that i can integrate more features in the package?

**Comment by GokulNC** [comment]
This one small function is the only important part of the library:
https://github.com/narVidhai/Google-Transliterate-API/blob/415dfe66d3839af8c95cc7fc51cc052c4c72a902/google/transliteration/transliterate.py#L11

The response of the API call is provided by Google, and I am not sure about the exact full format since I take only the transliteration suggestions from the HTTP response. You can try printing the JSON response to see its format if you feel that is of importance to your work.

**Comment by jaydangar** [comment]
@GokulNC Thanks got the idea, thank you again.
